GET http://localhost:8080/get_book/all

###
GET http://localhost:8080/get_book/id/634f952fc707343881661ed5

###
GET http://localhost:8080/get_book/category/chemistry

###
POST http://localhost:8080/add_book
Content-Type: application/json

{
    "book_name": "Book9",
    "category": "history"
}

###
PUT http://localhost:8080/update_book
Content-Type: application/json

{
    "id": "634f952fc707343881661ed5",
    "update": {
        "book_name": "Theory of nothing",
        "category": "physics"
    }
}

###
DELETE http://localhost:8080/delete_book
Content-Type: application/json

{
    "id": "634f9527c707343881661ed3"
}